development: &default
  omniauth_provider_key: omniauth_provider_key
  omniauth_provider_secret: omniauth_provider_secret
  domain_name: example.com
  secret_key_base: my-secret

test:
  <<: *default
