default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "secret_key" %>
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  slack_token: <%= ENV["SLACK_TOKEN"] %>
  rollbar_token: <%= ENV["ROLLBAR_TOKEN"] %>
  slack_enabled: <%= ENV["SLACK_ENABLED"] %>
  sendgrid_user_name: <%= ENV["SENDGRID_USER_NAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain: <%= ENV["DOMAIN"] %>
  default_from_email: <%= ENV["DEFAULT_FROM_EMAIL"] || "test@example.com" %>
  dataguru:
    api_url: <%= ENV["DATAGURU_API_URL"] %>
    access_token: <%= ENV["DATAGURU_ACCESS_TOKEN"] %>
  jira:
    username: <%= ENV["JIRA_USERNAME"] %>
    password: <%= ENV["JIRA_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
